import type {
  Listing,
  LandlordDashboardMetrics,
  LeadRequest,
  MonetizationBoost,
  AdminQueueItem,
} from "@/types/domain";

const PHOTO = (seed: string, w = 800, h = 600) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "lst_001",
    title: "Sunny self-contained cottage near UZ",
    area: "Mount Pleasant",
    coordinates: { lat: -17.7886, lng: 31.0492 },
    address: "14 Glenara Avenue, Mount Pleasant, Harare",
    pricePerMonthUsd: 180,
    roomType: "self_contained",
    occupancyLimit: 1,
    utilities: ["borehole", "wifi", "solar", "fenced_yard"],
    media: [
      { id: "m1", url: PHOTO("hbu-mp-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-mp-2"), type: "photo" },
      { id: "m3", url: PHOTO("hbu-mp-3"), type: "photo" },
      { id: "m4", url: PHOTO("hbu-mp-4"), type: "photo" },
    ],
    verification: "verified",
    rating: 4.8,
    reviewCount: 23,
    distanceToCampusKm: 1.2,
    houseRules: ["No overnight guests after 10pm", "No smoking indoors", "Quiet hours 9pm–6am"],
    description:
      "Bright, freshly painted self-contained cottage in a quiet, leafy Mount Pleasant cul-de-sac, a short walk from the University of Zimbabwe main gate. Reliable borehole backup and solar inverter mean you'll never be without water or light during load-shedding.",
    landlord: {
      id: "lnd_01",
      name: "Mrs. Tendai Chikuni",
      avatarUrl: PHOTO("landlord-1", 100, 100),
      isVerified: true,
      responseRateApprox: 96,
      memberSince: "2022-03-01",
      phoneVisible: true,
    },
    createdAt: "2026-05-12T08:00:00Z",
  },
  {
    id: "lst_002",
    title: "Modern shared house, walk to Belgravia campus",
    area: "Belgravia",
    coordinates: { lat: -17.8067, lng: 31.0445 },
    address: "8 Lanark Road, Belgravia, Harare",
    pricePerMonthUsd: 140,
    roomType: "shared_double",
    occupancyLimit: 2,
    utilities: ["wifi", "prepaid_electricity", "security_guard", "furnished"],
    media: [
      { id: "m1", url: PHOTO("hbu-bg-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-bg-2"), type: "photo" },
      { id: "m3", url: PHOTO("hbu-bg-3"), type: "photo" },
    ],
    verification: "verified",
    rating: 4.5,
    reviewCount: 11,
    distanceToCampusKm: 0.6,
    houseRules: ["Visitors must sign in with guard", "No pets", "Shared kitchen cleaning roster"],
    description:
      "Furnished double room in a secure, guarded compound with three other students. Strong fibre Wi-Fi throughout, prepaid ZESA meter so you only pay for what you use, and a five-minute walk to lecture halls.",
    landlord: {
      id: "lnd_02",
      name: "Mr. Farai Moyo",
      avatarUrl: PHOTO("landlord-2", 100, 100),
      isVerified: true,
      responseRateApprox: 88,
      memberSince: "2021-09-15",
      phoneVisible: true,
    },
    createdAt: "2026-05-20T08:00:00Z",
  },
  {
    id: "lst_003",
    title: "Budget single room, Avondale shops nearby",
    area: "Avondale",
    coordinates: { lat: -17.7989, lng: 31.0364 },
    address: "22 King George Road, Avondale, Harare",
    pricePerMonthUsd: 95,
    roomType: "single",
    occupancyLimit: 1,
    utilities: ["borehole", "fenced_yard"],
    media: [
      { id: "m1", url: PHOTO("hbu-av-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-av-2"), type: "photo" },
    ],
    verification: "pending",
    rating: undefined,
    reviewCount: 0,
    distanceToCampusKm: 3.1,
    houseRules: ["No loud music after 8pm"],
    description:
      "Affordable single room in a fenced family yard close to Avondale shopping centre, kombi routes, and the flea market. Great for students on a tighter budget who don't mind a slightly longer commute to campus.",
    landlord: {
      id: "lnd_03",
      name: "Mr. Tafadzwa Banda",
      avatarUrl: PHOTO("landlord-3", 100, 100),
      isVerified: false,
      responseRateApprox: 61,
      memberSince: "2026-01-10",
      phoneVisible: false,
    },
    createdAt: "2026-06-01T08:00:00Z",
  },
  {
    id: "lst_004",
    title: "Triple room near Chinhoyi University access road",
    area: "Chinhoyi (CUT proximity)",
    coordinates: { lat: -17.3667, lng: 30.2 },
    address: "Off Magamba Way, Chinhoyi",
    pricePerMonthUsd: 75,
    roomType: "shared_triple",
    occupancyLimit: 3,
    utilities: ["solar", "borehole", "study_table"],
    media: [
      { id: "m1", url: PHOTO("hbu-cut-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-cut-2"), type: "photo" },
      { id: "m3", url: PHOTO("hbu-cut-3"), type: "photo" },
    ],
    verification: "verified",
    rating: 4.2,
    reviewCount: 8,
    distanceToCampusKm: 0.9,
    houseRules: ["Lights out 11pm on weekdays", "Cleaning rota enforced"],
    description:
      "Solar-powered triple room a short walk from the CUT access road — popular with first and second-year students. Each bed has its own study table and lockable cupboard.",
    landlord: {
      id: "lnd_04",
      name: "Mrs. Grace Mutasa",
      avatarUrl: PHOTO("landlord-4", 100, 100),
      isVerified: true,
      responseRateApprox: 91,
      memberSince: "2020-11-02",
      phoneVisible: true,
    },
    createdAt: "2026-04-28T08:00:00Z",
  },
  {
    id: "lst_005",
    title: "Hillside cottage with garden, very secure",
    area: "Hillside",
    coordinates: { lat: -17.819, lng: 31.0815 },
    address: "5 Coronation Avenue, Hillside, Harare",
    pricePerMonthUsd: 210,
    roomType: "cottage",
    occupancyLimit: 2,
    utilities: ["wifi", "solar", "borehole", "security_guard", "furnished"],
    media: [
      { id: "m1", url: PHOTO("hbu-hs-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-hs-2"), type: "photo" },
      { id: "m3", url: PHOTO("hbu-hs-3"), type: "photo" },
      { id: "m4", url: PHOTO("hbu-hs-4"), type: "photo" },
      { id: "m5", url: PHOTO("hbu-hs-5"), type: "photo" },
    ],
    verification: "verified",
    rating: 4.9,
    reviewCount: 31,
    distanceToCampusKm: 4.4,
    houseRules: ["No subletting", "Garden upkeep shared", "No parties"],
    description:
      "A genuinely premium option: fully furnished cottage with its own garden, 24-hour guard, solar backup and borehole. Ideal for postgraduate students or final-years who want quiet, dependable comfort.",
    landlord: {
      id: "lnd_05",
      name: "Dr. Patience Sibanda",
      avatarUrl: PHOTO("landlord-5", 100, 100),
      isVerified: true,
      responseRateApprox: 99,
      memberSince: "2019-06-20",
      phoneVisible: true,
    },
    createdAt: "2026-03-15T08:00:00Z",
  },
  {
    id: "lst_006",
    title: "Marlborough shared double, close to industrial site internships",
    area: "Marlborough",
    coordinates: { lat: -17.7775, lng: 30.9967 },
    address: "61 Birmingham Road, Marlborough, Harare",
    pricePerMonthUsd: 110,
    roomType: "shared_double",
    occupancyLimit: 2,
    utilities: ["wifi", "prepaid_electricity"],
    media: [
      { id: "m1", url: PHOTO("hbu-mb-1"), type: "photo" },
      { id: "m2", url: PHOTO("hbu-mb-2"), type: "photo" },
    ],
    verification: "rejected",
    rating: undefined,
    reviewCount: 0,
    distanceToCampusKm: 6.8,
    houseRules: ["No overnight guests"],
    description:
      "Listing currently under review — documentation for water source and electrical safety certificate pending resubmission by landlord.",
    landlord: {
      id: "lnd_06",
      name: "Mr. Joseph Chiweshe",
      isVerified: false,
      responseRateApprox: 40,
      memberSince: "2026-06-05",
      phoneVisible: false,
    },
    createdAt: "2026-06-10T08:00:00Z",
  },
];

export const MOCK_LANDLORD_METRICS: LandlordDashboardMetrics = {
  totalViews: 4218,
  viewsDeltaPct: 12.4,
  totalLeads: 37,
  leadsDeltaPct: 8.1,
  earningsUsd: 1840,
  earningsDeltaPct: -3.2,
  activeListings: 4,
};

export const MOCK_LEADS: LeadRequest[] = [
  {
    id: "lead_01",
    listingId: "lst_001",
    listingTitle: "Sunny self-contained cottage near UZ",
    studentName: "Rutendo Marufu",
    studentAvatarUrl: PHOTO("student-1", 100, 100),
    message: "Hi, is the cottage still available from the 1st of July? I'm a 3rd year Engineering student.",
    requestedAt: "2026-06-17T14:22:00Z",
    status: "new",
    channel: "message",
  },
  {
    id: "lead_02",
    listingId: "lst_002",
    listingTitle: "Modern shared house, walk to Belgravia campus",
    studentName: "Tanaka Hove",
    studentAvatarUrl: PHOTO("student-2", 100, 100),
    message: "Could you call me back about the deposit terms?",
    requestedAt: "2026-06-16T09:05:00Z",
    status: "responded",
    channel: "callback",
  },
  {
    id: "lead_03",
    listingId: "lst_001",
    listingTitle: "Sunny self-contained cottage near UZ",
    studentName: "Blessing Nyathi",
    studentAvatarUrl: PHOTO("student-3", 100, 100),
    message: "Does the price include water and electricity?",
    requestedAt: "2026-06-14T18:40:00Z",
    status: "closed",
    channel: "message",
  },
];

export const MOCK_BOOSTS: MonetizationBoost[] = [
  {
    id: "boost_top",
    name: "Top of Search Bump",
    description: "Pin your listing to the top 3 results for your area for 7 days.",
    priceUsd: 12,
    durationDays: 7,
    icon: "rocket",
  },
  {
    id: "boost_badge",
    name: "Verified Badge Placement",
    description: "Highlight your verified status with a featured badge across search and map views.",
    priceUsd: 6,
    durationDays: 30,
    icon: "shield",
  },
  {
    id: "boost_featured",
    name: "Homepage Spotlight",
    description: "Appear in the curated 'Featured this week' rail shown to new students.",
    priceUsd: 20,
    durationDays: 7,
    icon: "star",
  },
];

export const MOCK_ADMIN_QUEUE: AdminQueueItem[] = MOCK_LISTINGS.filter((l) => l.verification !== "verified").map(
  (l, i) => ({
    id: `queue_${i}`,
    listing: l,
    submittedAt: l.createdAt,
    flagCount: i === 0 ? 0 : i,
    documentsAttached: i % 2 === 0,
  })
);
